// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_league_stats_proc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_league_stats_proc));
        
        string IMigrationMetadata.Id
        {
            get { return "201801301759540_add_league_stats_proc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
